# I only commit this file for demonstration purposes. In a real-world scenario, this file should be added to .gitignore
my_api_secret_key = "this_is_my_dummy_api_secret_key"

[destination.postgres.credentials]
database = "postgres"
password = "abcd1234"
username = "postgres"
host = "localhost"
port = 5432
connect_timeout = 15
